version: '3.3'

services:
  app:
    build:
      context: .
    ports:
      - 5000:80
  
  prometheus:
    image: prom/prometheus:v2.47.0
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - app

volumes:
  prometheus-data: